"""Create the PostgreSQL baseline schema.

Revision ID: 0001_postgresql_baseline
Revises:
"""

from alembic import op


revision = "0001_postgresql_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE alerts (
            id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            source_category TEXT NOT NULL DEFAULT 'other',
            source_system TEXT,
            source_product TEXT,
            alert_type TEXT,
            severity TEXT NOT NULL DEFAULT 'medium',
            status TEXT NOT NULL DEFAULT 'pending',
            conclusion TEXT,
            close_reason TEXT,
            owner TEXT,
            created_by TEXT,
            updated_by TEXT,
            occurred_at TEXT,
            discovered_at TEXT,
            description TEXT,
            key_evidence TEXT,
            evidence_info TEXT,
            handling_suggestion TEXT,
            handlers TEXT,
            raw_content TEXT,
            normalized_fields TEXT,
            round INTEGER NOT NULL DEFAULT 1,
            version INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE attachments (
            id TEXT PRIMARY KEY,
            alert_id TEXT REFERENCES alerts(id) ON DELETE CASCADE,
            file_type TEXT,
            filename TEXT NOT NULL,
            original_name TEXT,
            rel_path TEXT NOT NULL,
            size BIGINT NOT NULL DEFAULT 0,
            mime TEXT,
            description TEXT,
            uploaded_by TEXT,
            uploaded_at TEXT NOT NULL
        );

        CREATE TABLE entities (
            id TEXT PRIMARY KEY,
            alert_id TEXT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
            entity_type TEXT NOT NULL,
            value TEXT NOT NULL,
            role TEXT DEFAULT 'indicator',
            confidence DOUBLE PRECISION DEFAULT 1.0,
            source TEXT DEFAULT 'auto',
            created_at TEXT NOT NULL,
            UNIQUE(alert_id, entity_type, value, role)
        );

        CREATE TABLE notes (
            id TEXT PRIMARY KEY,
            alert_id TEXT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
            author TEXT,
            note_type TEXT NOT NULL DEFAULT 'manual',
            content TEXT NOT NULL,
            round INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        );

        CREATE TABLE assignment_logs (
            id TEXT PRIMARY KEY,
            alert_id TEXT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
            assigned_by TEXT,
            from_owner TEXT,
            to_owner TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE escalation_records (
            id TEXT PRIMARY KEY,
            alert_id TEXT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
            escalated_by TEXT,
            target_team TEXT,
            severity TEXT,
            reason TEXT,
            action_required TEXT,
            due_at TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE audit_logs (
            audit_seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
            id TEXT PRIMARY KEY,
            actor TEXT,
            actor_user_id TEXT,
            action TEXT NOT NULL,
            target_type TEXT NOT NULL,
            target_id TEXT,
            before_data TEXT,
            after_data TEXT,
            created_at TEXT NOT NULL,
            prev_hash TEXT,
            entry_hash TEXT
        );

        CREATE TABLE subtasks (
            id TEXT PRIMARY KEY,
            alert_id TEXT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            team TEXT,
            assignee TEXT,
            status TEXT NOT NULL DEFAULT 'todo',
            due_at TEXT,
            round INTEGER NOT NULL DEFAULT 1,
            version INTEGER NOT NULL DEFAULT 1,
            created_by TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE users (
            id TEXT PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            display_name TEXT,
            password_hash TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            must_change_password INTEGER NOT NULL DEFAULT 0,
            failed_login_count INTEGER NOT NULL DEFAULT 0,
            locked_until TEXT,
            email TEXT,
            phone TEXT,
            last_login_at TEXT,
            created_by TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE roles (
            id TEXT PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            description TEXT,
            is_system INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE user_roles (
            user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
            granted_by TEXT,
            granted_at TEXT NOT NULL,
            PRIMARY KEY (user_id, role_id)
        );

        CREATE TABLE sessions (
            token TEXT PRIMARY KEY,
            user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            created_at TEXT NOT NULL,
            last_seen_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            ip TEXT,
            user_agent TEXT,
            csrf_hash TEXT,
            revoked INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE api_tokens (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            token_prefix TEXT NOT NULL,
            token_hash TEXT NOT NULL UNIQUE,
            scopes TEXT NOT NULL,
            created_by TEXT,
            created_at TEXT NOT NULL,
            last_used_at TEXT,
            expires_at TEXT,
            revoked INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE permissions (
            code TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT
        );

        CREATE TABLE role_permissions (
            role_code TEXT NOT NULL,
            permission_code TEXT NOT NULL,
            PRIMARY KEY (role_code, permission_code)
        );

        CREATE TABLE auth_meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        );

        CREATE INDEX idx_alerts_updated_at ON alerts(updated_at DESC);
        CREATE INDEX idx_alerts_status_updated ON alerts(status, updated_at DESC);
        CREATE INDEX idx_alerts_severity_updated ON alerts(severity, updated_at DESC);
        CREATE INDEX idx_alerts_source_category_updated
            ON alerts(source_category, updated_at DESC);
        CREATE INDEX idx_alerts_owner_updated ON alerts(owner, updated_at DESC);
        CREATE INDEX idx_entities_value ON entities(value);
        CREATE INDEX idx_entities_alert ON entities(alert_id);
        CREATE INDEX idx_entities_type_value ON entities(entity_type, value);
        CREATE INDEX idx_attachments_alert ON attachments(alert_id);
        CREATE INDEX idx_notes_alert_created ON notes(alert_id, created_at DESC);
        CREATE INDEX idx_assignment_alert ON assignment_logs(alert_id);
        CREATE INDEX idx_escalation_alert ON escalation_records(alert_id);
        CREATE INDEX idx_subtasks_alert ON subtasks(alert_id);
        CREATE INDEX idx_audit_created_seq
            ON audit_logs(created_at DESC, audit_seq DESC);
        CREATE INDEX idx_audit_target ON audit_logs(target_type, target_id);
        CREATE INDEX idx_sessions_user ON sessions(user_id);
        CREATE INDEX idx_sessions_expires ON sessions(expires_at);
        CREATE INDEX idx_user_roles_user ON user_roles(user_id);
        CREATE INDEX idx_api_tokens_hash ON api_tokens(token_hash);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS auth_meta;
        DROP TABLE IF EXISTS role_permissions;
        DROP TABLE IF EXISTS permissions;
        DROP TABLE IF EXISTS api_tokens;
        DROP TABLE IF EXISTS sessions;
        DROP TABLE IF EXISTS user_roles;
        DROP TABLE IF EXISTS roles;
        DROP TABLE IF EXISTS users;
        DROP TABLE IF EXISTS subtasks;
        DROP TABLE IF EXISTS audit_logs;
        DROP TABLE IF EXISTS escalation_records;
        DROP TABLE IF EXISTS assignment_logs;
        DROP TABLE IF EXISTS notes;
        DROP TABLE IF EXISTS entities;
        DROP TABLE IF EXISTS attachments;
        DROP TABLE IF EXISTS alerts;
        """
    )
